
team_notification_email:  'team@giftstarter.com'
product_api_url:          'https://product-dev-gift-starter.appspot.com/static'

app_url:                  'https://www.giftstarter.com'
email_url:                'http://www.giftstarter.com/email/send.json'
storage_url:              '/giftstarter-pictures/'

facebook_app:             'giftstarterapp'
facebook_app_id:          '301135316704582'

baseServiceFeeRate:       0.08

couponCodes:               ['GiftMe!','CollisionGift','Collision15','StartupGift','GiftFriend','GiftPartner','GiftItForward','9MileLabsGift','Level3Gift','Logic2020Gift','PathwiseGift','ProductHunt8','Yunderson15','GiftMe8','Facebook8','LenatiGift','SurfGift8','TactileGift8','BandHGift','ButterGift','FatCorkGift','SturtevantsGift']

googleanalytics:
  key:                    'UA-51616127-6'

mixpanel:
  key:                    'e62cefc2003d70c2c10c3fdb1fc46917'

prosperent:
  key:                    '0ea6828d486ddb94138d277e9007790b'

heap:
  key:                    '4144879771'

cardprocessor:            'paypal'
