
team_notification_email:  'test@giftstarter.co'

app_url:                  'https://www.dev.giftstarter.co'
email_url:                'http://email.dev.giftstarter.co'
storage_url:              '/giftstarter-pictures/dev/'

googleanalytics:
  key:                    'UA-51616127-3'

mixpanel:
  key:                    '2cfdda518bed5ee0bc7e9ad48c8c8f48'