
team_notification_email:  'team@giftstarter.co'
product_api_url:          'https://product-dev-gift-starter.appspot.com/static'

app_url:                  'https://www.giftstarter.co'
email_url:                'http://www.giftstarter.co/email/send.json'
storage_url:              '/giftstarter-pictures/'

facebook_app:             'giftstarterapp'
facebook_app_id:          '301135316704582'

googleanalytics:
  key:                    'UA-51616127-2'

mixpanel:
  key:                    'e62cefc2003d70c2c10c3fdb1fc46917'

prosperent:
  key:                    '0ea6828d486ddb94138d277e9007790b'

heap:
  key:                    '1741795975'
